/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuList: typeof import('./components/MenuList.vue')['default']
    RestaurantMenu: typeof import('./components/RestaurantMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideShow: typeof import('./components/SlideShow.vue')['default']
    StarFall: typeof import('./components/StarFall.vue')['default']
  }
}
